// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActiveUser(ctx context.Context, id pgtype.UUID) error
	ActiveUserAdmin(ctx context.Context, id pgtype.UUID) error
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CreateEmailVertify(ctx context.Context, arg CreateEmailVertifyParams) (EmailVertify, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreatePermissionIfNotExists(ctx context.Context, arg CreatePermissionIfNotExistsParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateRoleIfNotExists(ctx context.Context, arg CreateRoleIfNotExistsParams) error
	CreateRolePermissionIfNotExists(ctx context.Context, arg CreateRolePermissionIfNotExistsParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserIfNotExists(ctx context.Context, arg CreateUserIfNotExistsParams) error
	CreateUserRoleIfNotExists(ctx context.Context, arg CreateUserRoleIfNotExistsParams) error
	DeActiveUser(ctx context.Context, id pgtype.UUID) error
	DeActiveUserAdmin(ctx context.Context, id pgtype.UUID) error
	DeactivateEmailVertifyByID(ctx context.Context, id string) error
	DeleteEmailVertify(ctx context.Context, id string) error
	DeleteExpiredSessions(ctx context.Context) error
	DeletePermission(ctx context.Context, id int32) error
	DeleteRole(ctx context.Context, id int32) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteSessionByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	ForceClearAllSessions(ctx context.Context) error
	GetEmailVertify(ctx context.Context, id string) (EmailVertify, error)
	GetEmailVertifyByEmail(ctx context.Context, email string) ([]EmailVertify, error)
	GetPermissionByID(ctx context.Context, id int32) (Permission, error)
	GetPermissionByName(ctx context.Context, name string) (Permission, error)
	GetRoleByID(ctx context.Context, id int32) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetRolePermissions(ctx context.Context, roleID int32) ([]Permission, error)
	GetSessionByAccessToken(ctx context.Context, accessToken string) (UserSession, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (UserSession, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (UserSession, error)
	GetSessionByRequestInfo(ctx context.Context, arg GetSessionByRequestInfoParams) (UserSession, error)
	GetSessionByUserID(ctx context.Context, userID pgtype.UUID) (UserSession, error)
	GetUserByAccount(ctx context.Context, account pgtype.Text) (User, error)
	GetUserByAccountAndPassword(ctx context.Context, account pgtype.Text) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserPermissions(ctx context.Context, id pgtype.UUID) ([]Permission, error)
	GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]Role, error)
	ListActiveSessionsByUserID(ctx context.Context, userID pgtype.UUID) ([]UserSession, error)
	ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]Permission, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) error
	RevokeSession(ctx context.Context, id pgtype.UUID) error
	UpdateEmailVertify(ctx context.Context, arg UpdateEmailVertifyParams) (EmailVertify, error)
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateSessionActivity(ctx context.Context, id pgtype.UUID) error
	UpdateSessionTokens(ctx context.Context, arg UpdateSessionTokensParams) (UserSession, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAccountAndPassword(ctx context.Context, arg UpdateUserAccountAndPasswordParams) error
}

var _ Querier = (*Queries)(nil)
