basePath: /api/v1
definitions:
  api.MetaData:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      total_count:
        type: integer
    type: object
  api.Response:
    properties:
      data:
        description: 不要使用omitempty 否則空list也會回傳null
      meta:
        $ref: '#/definitions/api.MetaData'
      success:
        type: boolean
    type: object
  api.ResponseError:
    properties:
      code:
        type: integer
      details:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
  github_com_RoyceAzure_lab_authcenter_internal_api_dto.AccountAndPasswordLoginDTO:
    properties:
      account:
        description: 帳號
        type: string
      password:
        description: 密碼明文
        type: string
    type: object
  github_com_RoyceAzure_lab_authcenter_internal_api_dto.CreateVertifyUserEmailLinkDTO:
    properties:
      email:
        type: string
    type: object
  github_com_RoyceAzure_lab_authcenter_internal_api_dto.GoogleLoginDTO:
    properties:
      id_token:
        type: string
    type: object
  github_com_RoyceAzure_lab_authcenter_internal_api_dto.LinkedUserAccountAndPasswordDTO:
    properties:
      account:
        type: string
      email:
        type: string
      password:
        type: string
    type: object
  github_com_RoyceAzure_lab_authcenter_internal_api_dto.LoginResponse:
    properties:
      access_token:
        $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.TokenInfo'
      refresh_token:
        $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.TokenInfo'
      user:
        $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.UserDTO'
    type: object
  github_com_RoyceAzure_lab_authcenter_internal_api_dto.PermissionsDTO:
    properties:
      actions:
        items:
          type: string
        type: array
      resource:
        type: string
    type: object
  github_com_RoyceAzure_lab_authcenter_internal_api_dto.RefreshTokenDTO:
    properties:
      refresh_token:
        type: string
    type: object
  github_com_RoyceAzure_lab_authcenter_internal_api_dto.TokenInfo:
    properties:
      expires_in:
        type: integer
      value:
        type: string
    type: object
  github_com_RoyceAzure_lab_authcenter_internal_api_dto.UserDTO:
    properties:
      account:
        type: string
      email:
        type: string
      facebook_id:
        type: string
      google_id:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      is_admin:
        type: boolean
      line_user_id:
        type: string
      name:
        type: string
    type: object
  github_com_RoyceAzure_lab_authcenter_internal_api_dto.UserPermissionsDTO:
    properties:
      is_admin:
        type: boolean
      resource:
        items:
          $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.PermissionsDTO'
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: 通用認證中心
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: authcenter
  version: "1.0"
paths:
  /auth/activate-user:
    post:
      consumes:
      - application/json
      parameters:
      - description: user_id
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                data:
                  type: string
              type: object
        "401":
          description: UnauthenticatedCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "460":
          description: InvalidArgumentCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 啟用用戶
      tags:
      - auth
  /auth/create-vertify-email:
    post:
      consumes:
      - application/json
      parameters:
      - description: email
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.CreateVertifyUserEmailLinkDTO'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                data:
                  type: string
              type: object
        "401":
          description: UnauthenticatedCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "460":
          description: InvalidArgumentCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
      summary: 創建email認證連結
      tags:
      - Register
  /auth/deactivate-user:
    post:
      consumes:
      - application/json
      parameters:
      - description: user_id
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                data:
                  type: string
              type: object
        "401":
          description: UnauthenticatedCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "460":
          description: InvalidArgumentCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 停用用戶
      tags:
      - auth
  /auth/linkedUser:
    post:
      consumes:
      - application/json
      parameters:
      - description: account info
        in: body
        name: accountInfo
        required: true
        schema:
          $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.LinkedUserAccountAndPasswordDTO'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
      summary: 使用帳號密碼連結email，必須要先認證email
      tags:
      - Register
  /auth/login/account:
    post:
      consumes:
      - application/json
      parameters:
      - description: account and password
        in: body
        name: accountInfo
        required: true
        schema:
          $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.AccountAndPasswordLoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.LoginResponse'
              type: object
        "401":
          description: UnauthenticatedCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "403":
          description: UnauthorizedCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
      summary: account and password login
      tags:
      - auth
  /auth/login/google:
    post:
      consumes:
      - application/json
      parameters:
      - description: google id token
        in: body
        name: id_token
        required: true
        schema:
          $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.GoogleLoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.LoginResponse'
              type: object
        "401":
          description: UnauthenticatedCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "403":
          description: UnauthorizedCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
      summary: google login
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      parameters:
      - description: refresh token
        in: body
        name: refresh_token
        required: true
        schema:
          $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.RefreshTokenDTO'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                data:
                  type: string
              type: object
        "401":
          description: UnauthenticatedCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "403":
          description: UnauthorizedCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
      summary: logout
      tags:
      - auth
  /auth/me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.UserDTO'
              type: object
        "403":
          description: UnauthorizedCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: get current login user info
      tags:
      - auth
  /auth/permissions:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.UserPermissionsDTO'
              type: object
        "401":
          description: UnauthenticatedCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "460":
          description: InvalidArgumentCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Get user permissions
      tags:
      - auth
  /auth/refresh-token:
    post:
      consumes:
      - application/json
      parameters:
      - description: refresh token
        in: body
        name: refresh_token
        required: true
        schema:
          $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.RefreshTokenDTO'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_RoyceAzure_lab_authcenter_internal_api_dto.TokenInfo'
              type: object
        "401":
          description: UnauthenticatedCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "403":
          description: UnauthorizedCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
      summary: renew token
      tags:
      - auth
  /auth/vertify-email:
    get:
      consumes:
      - application/json
      parameters:
      - description: code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/api.Response'
            - properties:
                data:
                  type: string
              type: object
        "401":
          description: UnauthenticatedCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "460":
          description: InvalidArgumentCode
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal server error
          schema:
            allOf:
            - $ref: '#/definitions/api.ResponseError'
            - properties:
                data:
                  type: string
              type: object
      summary: 驗證email認證連結
      tags:
      - Register
securityDefinitions:
  ApiKeyAuth:
    description: 'Description for Authorization header: Type "Bearer" followed by
      a space and the token. Example: "Bearer {token}"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
