version: "2"
sql:
  - engine: "postgresql"
    queries: "./query/"
    schema: "./migrations/"
    gen:
      go:
        package: "sqlc"
        out: "./sqlc"
        emit_json_tags: true
        sql_package: "pgx/v5"
        emit_prepared_queries: false
        emit_exact_table_names: false
        emit_empty_slices: true
        emit_interface: true
        overrides:
          - db_type: "timestamptz"
            go_type: "time.Time"
          - db_type: "numeric"
            go_type: "github.com/shopspring/decimal.Decimal"